### ISSUE TITLE
WP-China-Yes 设置页面风格修改为 WordPress 风格

### ISSUE THREAD

**Issue by AlanYe-Dev** [wp-china/wp-china-yes#31]
何时能将 WP-China-Yes 设置页面风格修改为 WordPress 风格 :-)

**Comment by sunxiyuan** [comment]
目前工作重心在自动化翻译系统上，WP-China-Yes插件暂时放一放。后面自动化翻译系统和协同翻译平台搞定了会回过头推进WP-China-Yes
