### ISSUE TITLE
Elementor Pro update fails

### ISSUE THREAD

**Issue by kdaye** [wp-china/wp-china-yes#33]
其他插件更新正常

Elementor Pro 2.9.2版本 to 2.10.3版本
更新失败：下载失败。 Forbidden

请问我该如何提供更多的信息？

**Comment by sunxiyuan** [comment]
付费版的插件是从插件开发者的服务器更新的，wordpress.org不对付费插件提供托管服务，所以WP-China-Yes插件也就未提供相应的加速资源。
这个问题在未来会解决（预计年底），我们会提供一个中国本土的特色商城，对这些付费应用统一提供托管、汉化和更新推送服务。
