### ISSUE TITLE
替换仪表盘的“WordPress活动及新闻”为本土社区提供的国内版

### ISSUE THREAD

**Issue by sunxiyuan** [wp-china/wp-china-yes#38]

**Comment by haoziz** [comment]
位于wp-admin/includes/dashboard.php line:1415

**Comment by sunxiyuan** [comment]
> 在wp-admin / includes / dashboard.php行：1415

删除了原版的小部件重新加了一个

**Comment by haoziz** [comment]
测试发现
line:1435的https://wordpress.org/news/feed/
line:1468的https://planet.wordpress.org/feed/
就是默认显示的。可以考虑直接替换这俩url。

**Comment by sunxiyuan** [comment]
> 测试发现
> line:1435的https://wordpress.org/news/feed/
> line:1468的https://planet.wordpress.org/feed/
> 就是默认显示的。可以考虑直接替换这俩url。

是可以的，我最开始忽略了rss默认会被缓存，是缓存导致的替换不生效。
不过有很多插件会在WordPress默认的这个新闻小部件中插入自己的新闻，比如说Yoast SEO，所以还是新写一个替换掉以前的

**Comment by haoziz** [comment]
> > 测试发现
> > line:1435的https://wordpress.org/news/feed/
> > line:1468的https://planet.wordpress.org/feed/
> > 就是默认显示的。可以考虑直接替换这俩url。
> 
> 是可以的，我最开始忽略了rss默认会被缓存，是缓存导致的替换不生效。
> 不过有很多插件会在WordPress默认的这个新闻小部件中插入自己的新闻，比如说Yoast SEO，所以还是新写一个替换掉以前的

哦
