### ISSUE TITLE
支持对WordPress管理后台的官方静态文件加速以应对小带宽服务器访问管理后台卡顿的问题

### ISSUE THREAD

**Issue by sunxiyuan** [wp-china/wp-china-yes#39]

**Comment by haoziz** [comment]
部分在wp-admin/load-scripts.php和wp-admin/load-styles.php用GET直接返回内容
部分在wp-admin/index.php直接用wp_enqueue_script钩子返回
比较分散，做替换的话较麻烦

**Comment by haoziz** [comment]
wp-includes/script-loader.php也有涉及

**Comment by sunxiyuan** [comment]
> 部分在wp-admin / load-scripts.php和wp-admin / load-styles.php用GET直接返回内容
> 部分在wp-admin / index.php直接用wp_enqueue_script钩子返回
> 比较分散，做替换的话较麻烦

这个功能放到3.1.0版本去推进了，3.0.0版本先专注把翻译校准搞好
