### ISSUE TITLE
更新时出现SSL错误

### ISSUE THREAD

**Issue by jackhhh** [wp-china/wp-china-yes#46]
使用主源出错：
```
正在从http://downloads.wordpress.org/release/zh_CN/wordpress-5.4.2.zip下载更新…
下载失败。: cURL error 51: SSL: certificate subject name '*.b0.upaiyun.com' does not match target host name 'd.w.org.ibadboy.net'
安装失败
```
使用备源：
```
正在从http://downloads.wordpress.org/release/zh_CN/wordpress-5.4.2.zip下载更新…
下载失败。: cURL error 35: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
安装失败
```
环境信息：
PHP7.2 阿里云虚拟主机

**Comment by sunxiyuan** [comment]
阿里云虚拟主机一直是存在这个问题的，原因不明。推测是因为服务器环境太老了，我依稀记得操作系统是centos 5，数据库是mysql 5.1，都是一批古董了……

**Comment by sunxiyuan** [comment]
这个问题暂时没有修复方案，sorry

**Comment by jackhhh** [comment]
我也觉得是虚拟主机的问题，正准备提个工单给阿里看看原因。
不过有个疑问是，不使用wp-china-yes而是直接改http proxy或者使用官方原有的网址是不会有这个问题的，是否是因为这个插件使用的东西不太一样？（还没来得及看具体代码）

**Comment by sunxiyuan** [comment]
> 
> 
> 我也觉得是虚拟主机的问题，正准备提个工单给阿里看看原因。
> 不过有个疑问是，不使用wp-china-yes而是直接改http proxy或者使用官方原有的网址是不会有这个问题的，看了眼代码也就是替换了一下网址，并没有更改获取包的方式，不知道这是为啥呢。
> 是否跟全站开启了https有关？（感觉应该也不会影响吧

wordpress官方api允许通过http直接访问，wp china yes的代理镜像只能用https访问，http会强制301到https上，因为害怕被劫持。也许使用http就不会产生问题了，但是我目前是无法提供http服务的，还是前面说的害怕被劫持，这种安全问题出现一次这个项目就完蛋了

**Comment by jackhhh** [comment]
工单确认了确实是系统太老了，当前虚机套餐的系统已经停止维护了，需要升级到独享套餐。感谢提供的信息~
