### ISSUE TITLE
有两个小问题

### ISSUE THREAD

**Issue by jingling2000** [wp-china/wp-china-yes#48]
我在使用的时候，在我本地出现了两个小问题。我想升级到wordpress5.5版本，但是我一点击更新，就出现下面的提示。
![微信截图_20200812183736](https://user-images.githubusercontent.com/32089660/90006308-3d1cf080-dccb-11ea-835a-ffd25a2a4991.png)
另外，不知道这个插件是否需要设置，因为，我每次一点击设置的时候就出现这样的现象。
![微信截图_20200812184118](https://user-images.githubusercontent.com/32089660/90006437-70f81600-dccb-11ea-88d6-96b935edbf35.png)
以上两点问题，不知道是什么原因造成的。希望能够得到帮助。。。

**Comment by sunxiyuan** [comment]
问题1：可否提供下你点击的“更新”按钮截图（全屏）？我怀疑你点错地方了
问题2：插件无需设置，点击启用即可。设置页无法查看可能是你的wp china yes插件的目录名不是wp-china-yes，修改一下就好了。

**Comment by jingling2000** [comment]
感谢您的耐心解答，这是我点击的升级位置（红框中的按钮）。
![微信截图_20200812193128](https://user-images.githubusercontent.com/32089660/90010569-a0f6e780-dcd2-11ea-9f90-106f31d8597c.png)

**Comment by jingling2000** [comment]
问题找到了，我在PHP中开启了opcache，把opcache关闭后，升级就正常了。

**Comment by sunxiyuan** [comment]
这个我确实没想到，感谢你的反馈，我会把这种情况整合到“常见问题”中，以求帮助更多人
