### ISSUE TITLE
Not friendly to WPMU

### ISSUE THREAD

**Issue by Creeper19472** [wp-china/wp-china-yes#49]
First I have to thank the author of this plugin. It's VERY useful for the users in China. But there is a problem about WPMU.
When this plugin is enabled on WPMU, the content of this plugin will display on the dashboard of the normal site instead of the dashboard of the network.
This is not a big problem for the general site network; but for users who commercialize the site network (using WP Ultimo) this is a problem.
So I hope you can adapt this plugin to WPMU as soon as possible.
Thanks.

**Comment by sunxiyuan** [comment]
I have noticed this problem and will fix it in a future version update
Thank you for your feedback

**Comment by sunxiyuan** [comment]
该问题已经在最新版本中修复，会给你推送更新的
