### ISSUE TITLE
一个插件已通过禁用wp_version_check()阻止了更新。

### ISSUE THREAD

**Issue by huaimingxiang** [wp-china/wp-china-yes#61]
你好，

一个插件已通过禁用wp_version_check()阻止了更新。
这个提示是对于插件的提示，我只是想确认下。

**Comment by sunxiyuan** [comment]
这个不是wp-china-yes触发的。
我估计你可能安装了优化类的插件吧，这类插件有时候确实会通过禁用更新的方式来加快后台访问速度。不过负面效果也显而易见——从此你只能手工检查更新了。

**Comment by huaimingxiang** [comment]
收到，谢谢
2020年12月4日 +0800 13:49 孙锡源 <notifications@github.com>，写道：
